WeatherWeb/WeatherWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("weather_show_app.urls")),  # 让app直接成为主页
    path('analysis/', include('analysis.urls'))  # 可视化的app

]

WeatherWeb/analysis/urls.py
from django.conf.urls import url

from . import views, graph_api_view

# 上面是api 的映射，下面是页面的url的映射，采用前后端分离的操作进行开发。
urlpatterns = [
                  url(r'^bar/$', graph_api_view.BarView.as_view(), name='demo'),
                  url(r'^geo/$', graph_api_view.GeoView.as_view(), name="geo"),
              ] + [
                  url(r'^index/$', views.IndexView, name='demo'),
              ]

WeatherWeb/weather_show_app/urls.py
# -*- coding: utf-8 -*-

from django.contrib.auth import views as auth_views
from django.urls import path

from weather_show_app import views, drawviews

app_name = "weather_show_app"  # 这儿需要设置这个来分辨不同的app

urlpatterns = [  # todo 记得要删除这些坏东西/
    path("index/", views.index, name="index"),
    path("", views.index, name='index'),
    path("loginpage/", views.loginPage, name="user_login"),
    path('logout/', views.userLogout, name="user_logout"),
    path("register/", views.register, name="user_register"),
    path("psssword-change/",
         auth_views.PasswordChangeView.as_view(template_name='weather_show_app/password_change_form.html',
                                               success_url='/index/'), name='password_change'),

    path('password-change-done/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name="/registration/password-change-done.html"), name="password_change_done"),

    path("detail/", views.detailView, name="detail"),
    path("detaillist/", views.detaillist, name="detaillist"),
    path("today_weather/", views.today_weather_page, name="today_weather"),
    path("favourite/", views.favouriteHandler.as_view(), name="Favourite"),

    # 可视化的接口
    path('bar/', drawviews.ChartView.as_view(), name='bar'),
    path("pie/", drawviews.PieView.as_view(), name="pie"),
    path('timeline/', drawviews.timeLineView.as_view(), name="timeline"),
    path("drawmap/", drawviews.drawMap.as_view(), name="drawMap"),
    path("get_today_aqi_line/", drawviews.get_today_aqi_bar.as_view(), name="get_today_aqi_line"),
    path("get_relative_humidity/", drawviews.get_today_average_humity.as_view(), name="draw_relative_humidity"),
    path("get_hostReplay/", drawviews.wind_graph.as_view(), name="get_hostReplay"),
    path("today_temperature_line/", drawviews.today_temperature_detail_line.as_view(), name="today_temperature_line"),
    # 这个改成了当踢的天气折线图

]

WeatherWeb/weather_show_app/models.py
from datetime import date

from django.contrib.auth.models import User
from django.db import models


class DateWeather(models.Model):  # 天气概括表 todo 敲里吗，调试一点都不好用！！！！！！！我
    class Meta:
        db_table = 'DateWeather'
        unique_together = ("date", "city")

    dressing_index = models.CharField(default="", max_length=50)  # 穿衣指数  # todo 保存哪儿需要改成update，看看怎么进行操作。
    dressing_index_desc = models.TextField(default="")  # 穿衣指数语言描述  # todo 保存哪儿需要改成update，看看怎么进行操作。

    humidity = models.FloatField()  # 湿度
    state = models.TextField()  # 晴朗，多云，大风，台风，暴雨，暴雪，～之类的
    date = models.DateField()
    update_date = models.DateField(auto_now=True)

    max_temperature = models.FloatField()  # 最高温和最低温
    min_temperature = models.FloatField()

    wind_power = models.TextField(blank=True, default="")  # 风力
    wind_direction = models.TextField(blank=True)  # 风向

    city = models.ForeignKey("City", related_name="City", on_delete=models.CASCADE)  # 这个是删除操作

    # extend_detail = models.TextField(blank=True)  # 这个是json的东西

    def __str__(self):
        return f"{self.date};{self.city}"


class HourWeather(models.Model):  # h每小时的具体的天气情况
    class Meta:
        db_table = 'HourWeather'

    Weather = models.ForeignKey("DateWeather", on_delete=models.CASCADE, related_name='DateWeather')

    belong_to_date = models.DateField(default=date.today)  # 这边也需要进行设置，这边的属于谁的日期需要增加。

    hour = models.IntegerField()
    temperature = models.FloatField()  # 最高温和最低温
    wind_power = models.FloatField(blank=True, default=0.0)  # 风力
    wind_direction = models.TextField(blank=True)  # 风向
    precipitation = models.FloatField()
    relative_humidity = models.IntegerField()
    AQI = models.IntegerField(blank=True, default=0)  # 空气质量

    def __str__(self):
        return f"{self.hour};{self.belong_to_date};{self.Weather}"


class City(models.Model):
    class Meta:
        db_table = 'City'

    name = models.CharField(max_length=50, unique=True)  # 城市名字
    pinyin = models.CharField(max_length=100, blank=True)  # 减少冗余的代价是时间代价
    code = models.CharField(max_length=20, blank=True)

    is_city = models.BooleanField(default=False)  # 地图只能显示地级市，而无法判断 城市内的区域，比如 南山
    direct_city_name = models.CharField(max_length=100, default="")  # 增加了城市名,脚本处理写入
    location = models.CharField(max_length=150, default="")  # 经纬度

    belong_province = models.CharField(max_length=100, default="")  # 属于的省份
    # 对应中国天气网的url code http://www.weather.com.cn/weather/101080101.shtml
    '''alter table City add COLUMN location varchar(150) default '' ;'''
    def __str__(self):
        return f"{self.name};"


class Favourite(models.Model):  # 收藏夹
    class Meta:
        db_table = 'Favourite'

    user = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)
    city = models.ManyToManyField('City', related_name="fav_city")

    def __str__(self):
        return f"{self.city};{self.user}"

WeatherWeb/weather_show_app/forms.py
# -*- coding: utf-8 -*-

"""
-------------------------------------------------
   File Name：     forms   
   Description :  
   Author :        zhengyimiing 
   date：          2020/3/26 
-------------------------------------------------
   Change Activity:
                   2020/3/26  
-------------------------------------------------
"""
from django.contrib.auth.models import User

__author__ = 'zhengyimiing'

from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'mdui-textfield-input', 'placeholder': "用户名"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'mdui-textfield-input', 'placeholder': "密码"}))  # 密码啊


class RegistrationForm(forms.ModelForm):  # 这个是注册表单的,表单继承model就是modelform
    username = forms.CharField(label="用户名",
                               widget=forms.TextInput(attrs={'class': 'mdui-textfield-input', 'placeholder': "用户名"}))
    password = forms.CharField(label="密码", widget=forms.PasswordInput(attrs={'class': 'mdui-textfield-input',
                                                                             'pattern': "^.*(?=.{8,})(?=.*[a-z])(?=.*[A-Z]).*$",
                                                                             'placeholder': "密码"}))
    password2 = forms.CharField(label="再次输入密码", widget=forms.PasswordInput(attrs={'class': 'mdui-textfield-input',
                                                                                  'pattern': "^.*(?=.{8,})(?=.*[a-z])(?=.*[A-Z]).*$",
                                                                                  'placeholder': "密码"}))
    email = forms.CharField(label='邮箱', widget=forms.EmailInput(
        attrs={'type': "email", 'class': 'mdui-textfield-input', 'placeholder': "密码"})
                            , error_messages={'required': "邮箱不能为空"})

    class Meta:
        model = User
        fields = ("username", "email")

        def clean_password2(self):
            cd = self.cleaned_data
            if cd['password'] != cd['password2']:
                raise forms.ValidationError("两次输入的密码不相同")
            return cd["password2"]

WeatherWeb/weather_show_app/views.py
import datetime
import json

import pandas as pd
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger  # 用来分页饿
from django.db import connection
from django.db.models import Count  # 直接使用models中的统计类来进行统计查询操作
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from rest_framework.views import APIView

from .forms import LoginForm, RegistrationForm
from .kmeans_process import get_similarity_city_controller
from .models import City, DateWeather, Favourite


def index(request):
    return render(request, 'weather_show_app/index_charts.html')


@login_required(login_url='/weather/loginpage/')  # 默认主页
def detailView(request):  # 详情页
    house_id = request.GET.get("house_id")
    houseList = City.objects.filter(Q(house_id=house_id)).order_by("-house_date")
    labels = houseList[0].house_labels.all()
    # print(labels)
    facility = houseList[0].house_facility.all()
    return render(request, "weather_show_app/index_chartspage_detail.html",
                  context={"house": houseList,
                           "house_id": house_id,
                           "labels": labels,
                           "facility": facility,
                           "app_name": "房源详情"
                           })


def testindex(request):  # 测试页
    # todo 提取不重复的日期的东西，然后进行年月日绘制图片进行查看可视化，同比环比，这个也是可以的
    result = fetchall_sql_dict("SELECT distinct(id),house_firstOnSale FROM `hotelapp_house` ")
    # print(result)
    # 然后转换成pandas进行一系列的筛选等
    # qs_dataframe = read_frame(qs=result)

    df = pd.DataFrame(result)  # 按月份
    df.index = pd.to_datetime(df.house_firstOnSale)
    return render(request, 'weather_show_app/test.html', context={"article": result})


# @login_required(login_url='/loginpage/')  # 详情页
def detaillist(request):  # 数据列表页分页
    today = datetime.datetime.now().date()
    date_weathers = DateWeather.objects.filter(date=today).order_by("-id").order_by("city_id")
    paginator = Paginator(date_weathers, 20)  # 2个一页的意思
    page = request.GET.get("page")
    try:
        current_page = paginator.page(page)
        date_weathers = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        date_weathers = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        date_weathers = current_page.object_list
    return render(request, "weather_show_app/index_chartspage_detaillist.html",
                  context={"app_name": "详细数据", "date_weathers": date_weathers, "page": current_page})
    # 这两个是必须要带上的属性


def fetchall_sql(sql) -> tuple:  # 这儿唯一有一个就是显示页面的
    # latest_question_list = KeyWordItem # 换成直接使用sql来进行工作
    with connection.cursor() as cursor:
        cursor.execute(sql)
        row = cursor.fetchall()
        # columns = [col[0] for col in cursor.description]  # 提取出column_name
        # return [dict(zip(columns, row)) for row in cursor.fetchall()][0]
        return row


def fetchall_sql_dict(sql) -> [dict]:  # 这儿唯一有一个就是显示页面的
    # latest_question_list = KeyWordItem # 换成直接使用sql来进行工作
    print("check sql")
    print(sql)
    with connection.cursor() as cursor:
        cursor.execute(sql)
        # row = cursor.fetchall()
        columns = [col[0] for col in cursor.description]  # 提取出column_name
        return [dict(zip(columns, row)) for row in cursor.fetchall()]


# @login_required(login_url='/loginpage/')  # 默认主页，主页不用登录，但是收藏夹需要登录
def index(request):  # 这儿唯一有一个就是显示页面的
    success_info = None
    if request.GET.get("success_info"):
        success_info = request.GET.get("success_info")
    # 总共的城市的数量
    count_city = City.objects.all().aggregate(count=Count("name", distinct=True))  # todo 花里胡哨的样式晚点再慢慢调整
    count_today = DateWeather.objects.all().aggregate(count=Count("id"))
    print(count_today)
    print(count_city)
    context = {
        'app_name': "天气分析",
        'count_today': count_today,  # None,  # count_today
        'count_today_city': count_city,  # None,  # count_today_city,  # 今天总共爬了多少个城市
        'count_total_city': None,  # count_total_city
        'success_info': success_info

    }
    return render(request, 'weather_show_app/index_chartspage.html', context)


def loginPage(request):  # 登陆界面的,这个是自定义的
    if request.method == "GET":
        success_info = None
        if request.session.get("success_info"):
            success_info = request.session.get("success_info")
            print("正在输出")
            print(request.session.get("success_info"))
            del request.session['success_info']  # 用完就删掉
            print("删除后")
            print(request.session.get("success_info"))
        login_form = LoginForm()
        return render(request, 'weather_show_app/loginPage.html',
                      context={'form': login_form, 'success_info': success_info})
    if request.method == "POST":
        login_form = LoginForm(request.POST)  # 这个
        if login_form.is_valid():
            cd = login_form.cleaned_data  # 转化成字段来方便提取
            user = authenticate(username=cd['username'], password=cd['password'])
            if user:
                login(request, user)
                # return HttpResponse("Wellcome!")
                return redirect('/')
            else:
                return render(request, 'weather_show_app/loginPage.html',
                              context={'form': login_form, "error": "账号或者密码错误！"})
        else:
            error = "请检查输入的账号和密码是否正确"
            login_form = LoginForm()
            return render(request, 'weather_show_app/loginPage.html', context={'form': login_form, "error": error})


def register(request):  # 注册用户User
    if request.method == "POST":
        user_form = RegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data["password"])
            # new_user.
            new_user.save()
            # 这儿放登陆注册的
            # loginForm = LoginForm()
            request.session['success_info'] = 'register_success'
            return redirect('/loginpage')  # todo 用命名空间的方式来进行操作
        else:
            return render(request, "weather_show_app/register.html", {"form": user_form,
                                                                      "error_message": "提交的账号密码不合法"})  # 这个是get的方式进来
    else:
        user_form = RegistrationForm()
        return render(request, "weather_show_app/register.html", {"form": user_form})  # 这个是get的方式进来


def userLogout(request):  # 登出
    logout(request)
    return redirect("/loginpage/")


def response_as_json(data):
    json_str = json.dumps(data)
    response = HttpResponse(
        json_str,
        content_type="application/json",
    )
    response["Access-Control-Allow-Origin"] = "*"
    return response


def json_response(data, code=200):
    data = {
        "code": code,
        "msg": "success",
        "data": data,
    }
    return response_as_json(data)


def json_error(error_string="error", code=500, **kwargs):
    data = {
        "code": code,
        "msg": error_string,
        "data": {}
    }
    data.update(kwargs)
    return response_as_json(data)


JsonResponse = json_response
JsonError = json_error


def today_weather_page(request):
    city_id = request.GET.get("city_id", 174)  # 174 是茂名
    city_name = request.GET.get("city_name", None)  # 174 是茂名
    city = City.objects.filter(name=city_name)
    if not city:
        now_city = City.objects.get(id=city_id)
    else:
        now_city = city[0]

    now_date = datetime.datetime.now().strftime('%Y-%m-%d')
    yesterday = (datetime.date.today() - datetime.timedelta(days=1)).strftime('%Y-%m-%d')

    select_date = request.GET.get("select_date", now_date)

    all_citys = City.objects.filter(is_city=True)
    today_weather = DateWeather.objects.get(city_id=now_city.id, date=select_date)
    future_date = (datetime.date.today() + datetime.timedelta(days=7)).strftime('%Y-%m-%d')
    past_dates = (datetime.date.today() - datetime.timedelta(days=7)).strftime('%Y-%m-%d')

    future_weathers = DateWeather.objects.filter(date__range=(now_date, future_date), city_id=city_id)
    past_weathers = DateWeather.objects.filter(date__range=(past_dates, yesterday), city_id=city_id).order_by("-date")
    past_weather_dates = [weather.date for weather in past_weathers]

    result = get_similarity_city_controller(city_id)

    return render(request, 'weather_show_app/index_chartspage_today_detail.html',
                  context={"app_name": "指定城市当天天气情况",
                           'all_citys': all_citys,
                           'test_vars': result,
                           "select_date": select_date,
                           "city_id": city_id, "now_city": now_city, "today_weather": today_weather,
                           "future_weathers": future_weathers, "past_dates": past_weather_dates})


# 搜索的页面
@login_required(login_url='/loginpage/')  # 默认主页
def searchPage(request):
    return render(request, 'weather_show_app/index_chartspage_search.html', context={"app_name": "查找房源"})


# 详细的页面
# @login_required(login_url='/loginpage/')  # 默认主页
def trainPage(request):
    return render(request, 'weather_show_app/test.html', context={"app_name": "test"})


def genFavtag(city_object: City, date_weather: DateWeather):  # 输入一个fav对象，生成一个house tag  # todo 收藏夹功能
    tag = f'''<tr id='tr-{city_object.id}'>
                <td>{city_object.id}</td>

            <td>{city_object.name}</td>
            <td>{date_weather.state}</td>
            <td>{date_weather.min_temperature}℃~~{date_weather.max_temperature}℃~</td>
            <td><a target="_blank" href="/host/?city_id={city_object.id}">{city_object.name}</a></td>
              <td>
                  <button  onclick="delete_btn({city_object.id})"  

WeatherWeb/weather_show_app/templates/weather_show_app/index_chartspage.html
{% extends 'weather_show_app/index_charts.html' %}
{#多app的方案中template需要这样来引入，view中也是需要加上#}
{#这个是默认的主页的页面#}
{% block title %}
{{ app_name }}
{% endblock %}

{% block drawer_body %}mdui-drawer-body-left{% endblock %}

{% block drawer_icon %}
    <span class=" mdui-btn mdui-btn-icon mdui-ripple mdui-ripple-white" mdui-drawer="{target: '#main-drawer', swipe: true}">
        <i class="mdui-icon material-icons">menu</i></span>
{% endblock %}

<!--侧边栏 todo 侧边栏晚点再把一个一个取掉把-->
{% block drawer %}
<div class="mdui-drawer " id="main-drawer">
  <div class="mdui-list" mdui-collapse="{accordion: true}" style="margin-bottom: 76px;">
    <div class="mdui-collapse-item mdui-collapse-item-open">
      <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
        <i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-blue">near_me</i>
        <div class="mdui-list-item-content">开始使用</div>
        <i class="mdui-collapse-item-arrow mdui-icon material-icons">keyboard_arrow_down</i>
      </div>
      <div class="mdui-collapse-item-body mdui-list mdui-collapse-item-open ">
      <a href="{%url 'weather_show_app:index' %}" class="mdui-list-item mdui-ripple mdui-list-item-active">数据概略</a>
        <a href="{% url 'weather_show_app:detaillist' %}" class="mdui-list-item mdui-ripple ">详细数据</a>
         </div>
  </div>

         <div class="mdui-collapse-item ">
      <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
        <!--<i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-blue">near_me</i>-->
        <i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-blue">insert_chart</i>
        <div class="mdui-list-item-content">分析</div>
          <!--<i class="mdui-collapse-item-arrow mdui-icon material-icons">insert_chart</i>-->
        <i class="mdui-collapse-item-arrow mdui-icon material-icons">keyboard_arrow_down</i>
      </div>
      <div class="mdui-collapse-item-body mdui-list mdui-collapse-item-open ">
           <a href="{% url 'weather_show_app:today_weather' %}" class="mdui-list-item mdui-ripple ">城市天气分析</a>

       <a ><div class="mdui-divider"></div></a>

    </div>
  </div>

  </div>
</div>
<a id="anchor-top"></a>
{% endblock %}



{% block app_name %}
{{ app_name }}
{% endblock %}

{% block name %}
{{ app_name }}
{% endblock %}

{% block content %}
<div class="mdui-container ">
{#    这儿才是内容的区域呢#}
  <h1 class="doc-title ">数据概览</h1>
  <div class="doc-intro mdui-typo">

<div class="mdui-container">


    <div class="mdui-valign mdui-center">
       <div class="mdui-chip ">
             <span class="mdui-chip-icon">🏆</span>
            <span id="count_today" class="mdui-chip-title">总过抓取的天气记录条数:{{ count_today.count }}</span>
        </div>
       <div class="mdui-chip ">
             <span class="mdui-chip-icon">🏠</span>
            <span class="mdui-chip-title">总共抓取直辖市或者区的总数:{{ count_today_city.count }}</span>
        </div>
<!--          <div class="mdui-chip ">-->
<!--             <span class="mdui-chip-icon">🏙</span>-->
<!--            <span class="mdui-chip-title">总共的城市数量:{{ count_total_city.count }}</span>-->
<!--        </div>-->

    </div>

<!--<div id="bar-hide">-->
<!--    <div class="mdui-center mdui-spinner mdui-spinner-colorful" style="margin-top: 220px;"></div>-->
<!--</div>-->
<!--    <div class="mdui-center" id="bar" style="width:800px; height:400px;margin-top:60px;display: none;"></div>  这儿给我去取掉了。暂时不弄这个了-->





    <br>
    <br>
    <div id="timeline-hide">
    <div class="mdui-center mdui-spinner mdui-spinner-colorful" style="margin-top: 200px;"></div>
</div>
    <div class="mdui-center" id="timeline" style="display:none;width:800px; height:400px; margin-top: 50px;"></div>


    <br>
    <div id="pieview-hide">
    <div class="mdui-center mdui-spinner mdui-spinner-colorful" style="margin-top: 200px;"></div>
    </div>
    <div class="mdui-center" id="pieview" style="display:none;width:800px; height:400px;margin-top: 50px;"></div>

{#这个是地图#}
        <br>
 <div id="drawmap-hide">
    <div class="mdui-center mdui-spinner mdui-spinner-colorful" style="margin-top: 200px;"></div>
</div>
    <div class="mdui-center" id="drawmap" style="display:none;width:800px; height:400px;margin-bottom: 50px;margin-top: 50px;"></div>


    </tbody>
  </table>
</div>


{% endblock %}


{% block tail %}
      <script>
        var chart = echarts.init(document.getElementById('bar'), 'black', {renderer: 'canvas'});

        $(
            function () {
                fetchbarData(chart);
                //setInterval(fetchbarData, 10000);

            }
        );

        function fetchbarData() {
            $.ajax({
                type: "GET",
                url: "{% url 'weather_show_app:bar' %}",
                dataType: 'json',
                async: true,
                timeout:5000,

                success: function (result) {
                    chart.setOption(result.data);
                    $('#bar-hide').css('display','none');  // 组件完全隐藏，不占用显示时占用的位置
                    $('#bar').css('display','block');   //在设置组件可以看
                },
                  error : function(XMLHttpRequest,status) { //请求完成后最终执行参数
                    if (status === 'timeout') {//超时,status还有success,error等值的情况
                        // temp2.abort();
                        $.ajax(this).abort();

                        // 　　　　　  alert("超时");
                        console.log("超时,已重试");
                        // temp2();
                        $.ajax(this);

                        return
                    }
                }
            });
        }
    </script>
    <script>
        var pie_chart = echarts.init(document.getElementById('pieview'), 'black', {renderer: 'canvas'});
        $(
            function () {
                fetchData(pie_chart);
                //setInterval(fetchData, 100000);
            }
        );

        function fetchData() {
            $.ajax({
                type: "GET",
                url: "{% url 'weather_show_app:pie' %}",
                dataType: 'json',
                async: true,
                timeout:5000,
                success: function (result) {
                    pie_chart.setOption(result.data);
                    $('#pieview-hide').css('display','none');  // 组件完全隐藏，不占用显示时占用的位置
                    $('#pieview').css('display','block');   //在设置组件可以看
                },
                  error : function(XMLHttpRequest,status) { //请求完成后最终执行参数
                    if (status === 'timeout') {//超时,status还有success,error等值的情况
                        // temp2.abort();
                        $.ajax(this).abort();

                        // 　　　　　  alert("超时");
                        console.log("超时,已重试");
                        // temp2();
                        $.ajax(this);

                        return
                    }
                }
            });
        }
    </script>
    <script>
        var timeline_chart = echarts.init(document.getElementById('timeline'), 'white', {renderer: 'canvas'});
        $(
            function () {
                fetchData_timeline(timeline_chart);
                //{#setInterval(fetchData_timeline, 10000);#}
            }
        );

        function fetchData_timeline() {
            $.ajax({
                type: "GET",
                url: "{% url 'weather_show_app:timeline' %} ",
                dataType: 'json',
                async: true,
                timeout:5000,
                success: function (result) {
                    timeline_chart.setOption(result.data);
                    $('#timeline-hide').css('display','none');  // 组件完全隐藏，不占用显示时占用的位置
                    $('#timeline').css('display','block');   //在设置组件可以看
                },

              error : function(XMLHttpRequest,status) { //请求完成后最终执行参数
                    if (status === 'timeout') {//超时,status还有success,error等值的情况
                        // temp2.abort();
                        $.ajax(this).abort();

                        // 　　　　　  alert("超时");
                        console.log("超时,已重试");
                        // temp2();
                        $.ajax(this);

                        return
                    }
                }
            });
        }
    </script>
    <script>
        var drawmap_chart = echarts.init(document.getElementById('drawmap'), 'white', {renderer: 'canvas'});
        $(
            function () {
                fetchData_drawmap(drawmap_chart);
                //{#setInterval(fetchData_drawmap, 10000);#}
            }
        );

        function fetchData_drawmap() {
            $.ajax({
                type: "GET",
                url: "{% url 'weather_show_app:drawMap' %}",
                dataType: 'json',
                async: true,
                timeout:5000,
                success: function (result) {
                    drawmap_chart.setOption(result.data);
                     $('#drawmap-hide').css('display','none');  // 组件完全隐藏，不占用显示时占用的位置
                    $('#drawmap').css('display','block');   //在设置组件可以看
                },

              error : function(XMLHttpRequest,status) { //请求完成后最终执行参数
                    if (status === 'timeout') {//超时,status还有success,error等值的情况
                        // temp2.abort();
                        $.ajax(this).abort();

                        // 　　　　　  alert("超时");
                        console.log("超时,已重试");
                        // temp2();
                        $.ajax(this);

                        return
                    }
                }

            });
        }
    </script>

{% endblock %}
  </div>

</div>

WeatherWeb/weather_show_app/templates/weather_show_app/select.html
{% for i in allcity %}
 <option value = "{{i.id}}"> {{i.city_nm}} </option>
{% endfor %}